
import Head from 'next/head'
import Image from 'next/image'

import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contect from '../components/Contect'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Sahil | Front-end Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
     
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contect/>
    </div>
  )
}
